guard 'haml' do
  watch(/^.+\.html\.haml$/)
end

guard 'livereload' do
  watch(/^.+\.html$/)
  watch(/^javascript\/+\.js$/)
end

# guard 'sass', :output => 'public/css'
# guard 'coffeescript', :input => 'public/javascript'

